//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet_vedom
{
    using System;
    using System.Collections.Generic;
    
    public partial class posech
    {
        public int id_posech { get; set; }
        public int id_uchenik { get; set; }
        public int po_uvaj { get; set; }
        public int po_neuvaj { get; set; }
        public int vsego { get; set; }
        public string chetvert { get; set; }
        public int ucheb_god { get; set; }
    }
}
