//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet_vedom
{
    using System;
    using System.Collections.Generic;
    
    public partial class predmet
    {
        public int id_predmet { get; set; }
        public string nazv { get; set; }
        public string uchitel { get; set; }
        public int kol_chasov { get; set; }
    }
}
