//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet_vedom
{
    using System;
    using System.Collections.Generic;
    
    public partial class roditeli
    {
        public int id_roditel { get; set; }
        public int id_uchenik { get; set; }
        public string step_rod { get; set; }
        public string FIO { get; set; }
        public string adres { get; set; }
        public string tel { get; set; }
        public string mest_rab { get; set; }
    }
}
