//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet_vedom
{
    using System;
    using System.Collections.Generic;
    
    public partial class roli
    {
        public int id_roli { get; set; }
        public string naim_roli { get; set; }
        public string login { get; set; }
        public string parol { get; set; }
    }
}
